on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install JDK 21
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-21-jdk  # Adjust the package name according to your requirements

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn -B clean install -DskipTests=true

      - name: Run Tests
        run: mvn -B test

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html