on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - develop

env:
  CLIENT_ID: ${{ vars.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  BOT_NAME: ${{ vars.BOT_NAME }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          architecture: 'x64'

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dmaven.test.skip=true

      - name: Archive compiled code
        uses: actions/upload-artifact@v4
        with:
          name: compiled-code
          path: target/

  unit-tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          architecture: 'x64'

      - name: Download compiled code
        uses: actions/download-artifact@v4
        with:
          name: compiled-code

      - name: Run Unit Tests
        run: mvn -B test -Dtest=unit/**/*

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  integration-tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          architecture: 'x64'

      - name: Download compiled code
        uses: actions/download-artifact@v4
        with:
          name: compiled-code

      - name: Run Integration Tests
        run: mvn -B verify -Dtest=bot/service/**/*
